# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-11 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentRFID', models.IntegerField(default=-1)),
                ('agentScore', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dumpYard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('severity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wasteManagement.Agent'),
        ),
        migrations.AddField(
            model_name='actions',
            name='yard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wasteManagement.dumpYard'),
        ),
    ]
